name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
    steps:
      - 
        name: Run graphql query to get tag
        uses: octokit/graphql-action@v2.x
        id: latest_tag
        with:
          variables: |
            repo: ${{ github.event.repository.name }}
            owner: linuxboot
          query: |
            query tag($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                refs(refPrefix: "refs/tags/", last: 1, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {
                  edges {
                    node {
                      name
               } } } } }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Parse tag from query output
        run: |
          #!/bin/bash
          latest_tag=$(echo '${{ steps.latest_tag.outputs.data }}' | jq '.repository.refs.edges[][].name' -r)
          [ -z "$latest_tag" ] && echo "Tag not found!" && exit 1
          [[ "$latest_tag" == "null" ]] && echo "Tag not found!" && exit 1
          [[ "$latest_tag" = v* ]] && latest_tag="${latest_tag:1}"
          echo "Found tag: \"${latest_tag}\"" 
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - 
        name: Check if the tag exists locally
        uses: action-pack/tag-exists@v1
        id: checkTag
        with: 
          tag: 'v${{ env.latest_tag }}'         
      -
        name: Finish when found
        run: |
          #!/bin/bash        
          val="${{ steps.checkTag.outputs.exists }}"
          echo "exists=${val}" >> $GITHUB_ENV
      -
        name: Checkout
        if: env.exists == 'false'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - 
        name: Lint Dockerfile
        if: env.exists == 'false'
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008,DL3059,DL3018 
          failure-threshold: warning          
      -
        name: Docker metadata
        id: meta
        if: env.exists == 'false'
        uses: docker/metadata-action@v5
        with:
          context: git
          images: |
            ${{ secrets.DOCKERHUB_REPO }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,priority=100
            type=raw,value=${{ env.latest_tag }}
          labels: |
            org.opencontainers.image.title=${{ vars.NAME }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - 
        name: Set up Docker Buildx
        if: env.exists == 'false'
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker image
        if: env.exists == 'false'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          provenance: false
          outputs: "type=local,dest=output"
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            VERSION_ARG=${{ steps.meta.outputs.version }}
      - 
        name: Rename binaries
        if: env.exists == 'false'
        run: |
          #!/bin/bash
          set -eu
          mv output/linux_amd64/utk.bin output/utk_${{ steps.meta.outputs.version }}_amd64.bin
          mv output/linux_arm64/utk.bin output/utk_${{ steps.meta.outputs.version }}_arm64.bin
          rm -rf output/linux_amd64 && rm -rf output/linux_arm64
      -
        name: Create a release
        if: env.exists == 'false'
        uses: action-pack/github-release@v2
        with:
          tag: "v${{ steps.meta.outputs.version }}"
          title: "v${{ steps.meta.outputs.version }}"
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Add binaries to release
        if: env.exists == 'false'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'output/*'
          release-tag: "v${{ steps.meta.outputs.version }}"
          repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Send mail
        if: env.exists == 'false'
        uses: action-pack/send-mail@v1
        with:
          to: ${{secrets.MAILTO}}
          from: Github Actions <${{secrets.MAILTO}}>
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Build of ${{ github.event.repository.name }} v${{ steps.meta.outputs.version }} completed
          body: |
              The build job of ${{ github.event.repository.name }} v${{ steps.meta.outputs.version }} was completed successfully! 
              
              See https://github.com/${{ github.repository }}/actions for more information.
